version: "3"
services:
  node:
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=poduction
    expose:
      - "3001"
    ports:
      - "3001:3001"
