[build]
  functions ="functions" 

[[redirects]]
  to="/.netlify/functions/app/:splat"
  from="/*"
  status=200
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    